import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type RecordItem = { id: string; name: string; email?: string; contact?: string; phone?: string; gst?: string; mobile?: string; pincode?: string; category?: string; location?: string; rate?: string; service?: string; brand?: string; area?: string; type?: string; days?: string; image?: string; code?: string; amount?: string; status?: string; date?: string; [key: string]: string | undefined };
export type Campaign = { id: string; jobCode: string; name: string; brand: string; location: string; channel: string; start: string; end: string; budget: string; assetIds: string[]; participants: string[]; status: string; creative?: string; notify?: string; progress?: number; proofDay?: number; reworkNote?: string; paid?: boolean };
export type Cart = Record<string, number>;
type DemoState = { agency: { name: string; business: string; address: string; contact: string; mobile: string; email: string; gst: string; code: string; [key: string]: string }; signedIn: boolean; brands: RecordItem[]; partners: RecordItem[]; assets: RecordItem[]; campaigns: Campaign[]; cart: Cart; orders: RecordItem[]; wallet?: number };
const initial: DemoState = {
 agency: { name:'Kraft Media Solutions', business:'OOH Media Agency', address:'Andheri West, Mumbai, Maharashtra', contact:'Aarav Mehta', mobile:'9876543210', email:'hello@kraftmedia.in', gst:'27AAECK1234F1Z5', code:'AGY-4827-1936' }, signedIn:false,
 brands:[{id:'BR-101',name:'RAMRAJ',email:'marketing@ramraj.in',contact:'Karthik Raman',phone:'9876501243',gst:'33AABCR1234L1Z2'},{id:'BR-102',name:'Bata',email:'brand@bata.in',contact:'Neha Shah',phone:'9811122000',gst:'27AAACB9876H1Z1'},{id:'BR-103',name:'NIKE',email:'media@nike.in',contact:'Riya Kapoor',phone:'9822212345',gst:'27AAACN4567H1Z4'},{id:'BR-104',name:'NIVEA',email:'team@nivea.in',contact:'Priya Nair',phone:'9888800000',gst:'27AAACN1245L1Z8'}],
 partners:[
  {id:'FAB-001',name:'Shree Fabrication Works',category:'Fabricators',location:'Chennai, T. Nagar',rate:'₹2,500/sq ft',contact:'Rahul Desai',mobile:'9876541234',email:'shree@example.com',pincode:'600017',gst:'33AABCM1234A1Z5',service:'ACP Board Fabrication'},
  {id:'FAB-002',name:'Metro Fabricators',category:'Fabricators',location:'Chennai, Guindy',rate:'₹2,450/sq ft',contact:'Mohan Kumar',mobile:'9876500012',email:'metro@example.com',pincode:'600032',gst:'33AABCM1234A1Z6',service:'MS Structure Fabrication'},
  {id:'PRN-001',name:'Chennai Print Hub',category:'Printers',location:'Chennai, T. Nagar',rate:'₹25/sq ft',contact:'Anita Rao',mobile:'9876554321',email:'print@example.com',pincode:'600017',gst:'33AABCC1234A1Z5',service:'Flex Printing'},
  {id:'PRN-002',name:'ColorMax Printers',category:'Printers',location:'Chennai, Anna Salai',rate:'₹35/sq ft',contact:'Kavya Nair',mobile:'9876554300',email:'color@example.com',pincode:'600002',gst:'33AABCC1234A1Z6',service:'Vinyl Printing'},
  {id:'LOG-001',name:'Sree Transport',category:'Logistics',location:'Chennai, T. Nagar',rate:'₹2,500/trip',contact:'Sameer Khan',mobile:'9898989898',email:'sree@example.com',pincode:'600017',gst:'33AABCL1234A1Z5',service:'City Delivery (Chennai)'},
  {id:'LOG-002',name:'FastMove Logistics',category:'Logistics',location:'Chennai, Guindy',rate:'₹18,000/trip',contact:'Farhan Ali',mobile:'9898989800',email:'fast@example.com',pincode:'600032',gst:'33AABCL1234A1Z6',service:'TN State Coverage'},
  {id:'INS-001',name:'Skyline Installers',category:'Installers',location:'Chennai, T. Nagar',rate:'₹15,000/site',contact:'Mohan Kumar',mobile:'9876512345',email:'skyline@example.com',pincode:'600017',gst:'33AABCI1234A1Z5',service:'Hoarding Installation'},
  {id:'INS-002',name:'ProMount Crew',category:'Installers',location:'Chennai, Anna Salai',rate:'₹18,000/site',contact:'Ajay Singh',mobile:'9876512300',email:'promount@example.com',pincode:'600002',gst:'33AABCI1234A1Z6',service:'Billboard Installation'}
 ],
 assets:[{id:'CH17-02-001',name:'Anna Salai Premium Billboard',brand:'Kraft Media Solutions',location:'Anna Salai, Chennai',pincode:'600002',rate:'₹18,50,000',amount:'₹4,000/day',area:'12 × 24 ft',type:'Static Billboard',days:'45',status:'Available for Sale',code:'ISTK-CH17-02-001',image:''},{id:'CH12-04-015',name:'Guindy Junction Billboard',brand:'City Media',location:'Guindy, Chennai',pincode:'600032',rate:'₹14,75,000',amount:'₹3,500/day',area:'10 × 20 ft',type:'Static Billboard',days:'30',status:'Available for Sale',code:'ISTK-CH12-04-015',image:''},{id:'CH08-06-023',name:'Velachery Main Road',brand:'Urban Ads',location:'Velachery, Chennai',pincode:'600042',rate:'₹28,00,000',amount:'₹5,000/day',area:'20 × 40 ft',type:'Unipole',days:'30',status:'Available for Sale',code:'ISTK-CH08-06-023',image:''}],
 campaigns:[{id:'CMP-001',jobCode:'JOB-CMP-001',name:'GRT Summer Collection 2026',brand:'GRT',location:'Chennai',channel:'Digital OOH',start:'2026-10-01',end:'2026-10-30',budget:'120000',assetIds:['CH17-02-001'],participants:['FAB-001'],status:'Pending'},{id:'CMP-002',jobCode:'JOB-CMP-002',name:'Bata Back to School 2026',brand:'Bata',location:'Chennai',channel:'Billboard',start:'2026-09-01',end:'2026-10-15',budget:'95000',assetIds:['CH12-04-015'],participants:['PRN-001'],status:'Approved',paid:true},{id:'CMP-003',jobCode:'JOB-CMP-003',name:'NIKE Move Chennai 2026',brand:'NIKE',location:'Chennai',channel:'Unipole',start:'2026-09-10',end:'2026-10-24',budget:'180000',assetIds:['CH08-06-023'],participants:['INS-001'],status:'Live',paid:true,progress:33,proofDay:15},{id:'CMP-004',jobCode:'JOB-CMP-004',name:'RAMRAJ Festive Collection 2026',brand:'RAMRAJ',location:'Chennai',channel:'Billboard',start:'2026-08-01',end:'2026-09-14',budget:'75000',assetIds:['CH17-02-001'],participants:['FAB-001','PRN-001','LOG-001','INS-001'],status:'Completed',paid:true,progress:100,proofDay:45}],cart:{},orders:[]
};
type Ctx = { data: DemoState; update: (patch: Partial<DemoState>)=>void; add: (key:'brands'|'partners'|'assets'|'campaigns'|'orders', item: any)=>void; changeCampaign:(id:string,patch:Partial<Campaign>)=>void };
const Context = createContext<Ctx | null>(null);
export function DemoProvider({children}:{children:ReactNode}) {
 const [data,setData]=useState<DemoState>(initial);
 useEffect(()=>{try { const stored=localStorage.getItem('taaraa-demo-v2'); if(stored){const saved=JSON.parse(stored) as Partial<DemoState>;setData({...initial,...saved,agency:{...initial.agency,...saved.agency},brands:saved.brands??initial.brands,partners:saved.partners??initial.partners,assets:saved.assets??initial.assets,campaigns:(saved.campaigns??initial.campaigns).map(c=>({...c,jobCode:c.jobCode||`JOB-${c.id}`}))})} } catch {} },[]);
 useEffect(()=>{try {localStorage.setItem('taaraa-demo-v2',JSON.stringify(data))} catch {}},[data]);
 const update=(patch:Partial<DemoState>)=>setData(d=>({...d,...patch}));
 const add=(key:'brands'|'partners'|'assets'|'campaigns'|'orders',item:any)=>setData(d=>({...d,[key]:[item,...(d[key] as any[])]}));
 const changeCampaign=(id:string,patch:Partial<Campaign>)=>setData(d=>({...d,campaigns:d.campaigns.map(c=>c.id===id?{...c,...patch}:c)}));
 return <Context.Provider value={{data,update,add,changeCampaign}}>{children}</Context.Provider>;
}
export function useDemo(){const ctx=useContext(Context);if(!ctx) throw new Error('Missing demo provider');return ctx}
export const money=(v:string|number)=>'₹'+Number(String(v).replace(/[^0-9.]/g,'')||0).toLocaleString('en-IN');
export const uid=(prefix:string)=>`${prefix}-${Math.floor(10000+Math.random()*90000)}`;
export const campaignJobCode=(campaign:Campaign)=>campaign.jobCode||`JOB-${campaign.id}`;
