import { useState } from 'react';
import { Link, useNavigate } from '@tanstack/react-router';
import { Eye, EyeOff, ArrowRight, Check } from 'lucide-react';
import city from '@/assets/city.jpg';
import { useDemo } from '@/lib/demo';
import { AllScreensMenu } from './all-screens';
import { Brand, Button, CopyButton, DownloadButton, GenericForm, Page } from './common';
export const agencyFields=[{label:'Agency Name',name:'name'},{label:'Business Type',name:'business',options:['OOH Media Agency','Advertising Agency','Brand','Media Owner']},{label:'Office Address',name:'address'},{label:'Contact Person',name:'contact'},{label:'Mobile Number',name:'mobile',type:'tel'},{label:'Email Address',name:'email',type:'email'},{label:'GST Number',name:'gst'}];
function AuthLayout({children}:{children:React.ReactNode}){return <div className="auth-screen"><img src={city} className="auth-city" alt="Illustrated city skyline with billboard"/><div className="auth-content"><div className="auth-header"><Link to="/" className="auth-logo"><Brand/></Link><AllScreensMenu/></div><p className="auth-tagline">Plan. Execute. Verify. Settle.</p>{children}</div></div>}
export function Welcome(){return <AuthLayout><div className="auth-card center-text"><div className="eyebrow">WELCOME TO TAARAA OS</div><h1>Agency Control Center</h1><p>Plan. Execute. Verify. Settle.</p><div className="auth-actions"><Button asChild><Link to="/register">Register Agency <ArrowRight size={15}/></Link></Button><Button variant="outline" asChild><Link to="/signin">Sign In</Link></Button></div><a href="mailto:support@taaraaos.example" className="muted-link">Need assistance?</a></div></AuthLayout>}
export function Register(){const {data,update}=useDemo();const navigate=useNavigate();return <AuthLayout><div className="auth-card auth-wide"><div className="eyebrow">NEW AGENCY</div><h1>Create your Agency account</h1><p>Sample company details are already filled. Continue without typing anything.</p><GenericForm fields={agencyFields} initial={data.agency} submit="Continue" onSubmit={v=>{update({agency:{...data.agency,...v,code:`AGY-${Math.floor(1000+Math.random()*9000)}-${Math.floor(1000+Math.random()*9000)}`}});navigate({to:'/register/review'})}}/></div></AuthLayout>}
export function Review(){const {data,update}=useDemo();const navigate=useNavigate();const [checks,setChecks]=useState([true,true,true]);return <AuthLayout><div className="auth-card auth-wide"><div className="eyebrow">FINAL STEP</div><h1>Review Agency details</h1><div className="review-list">{agencyFields.map(f=><div key={f.name}><span>{f.label}</span><strong>{data.agency[f.name] || '—'}</strong></div>)}</div><h3 className="section-label">Confirmation</h3>{['I confirm my mobile number is correct','I confirm my email address is correct','I agree to the Terms of Service and Privacy Policy'].map((t,i)=><label className="check-row" key={t}><input type="checkbox" checked={checks[i]} onChange={e=>setChecks(checks.map((v,n)=>n===i?e.target.checked:v))}/>{t}</label>)}<Button className="w-full mt-5" disabled={!checks.every(Boolean)} onClick={()=>{update({signedIn:true});navigate({to:'/register/success'})}}>Create Agency Account <ArrowRight size={15}/></Button></div></AuthLayout>}
export function RegisterSuccess(){const {data}=useDemo();return <AuthLayout><div className="auth-card center-text"><div className="success-mark"><Check/></div><h1>Agency account created successfully</h1><p>This Agency Code is used by stakeholders to connect with your agency.</p><div className="code-box"><small>Agency Code</small><strong>{data.agency.code}</strong><small>Keep this code handy for your records.</small></div><div className="stack-actions"><CopyButton value={data.agency.code||'AGY-4827-1936'}/><DownloadButton value={data.agency.code||'AGY-4827-1936'}/><Button asChild><Link to="/signin">Continue to Sign In <ArrowRight size={15}/></Link></Button></div></div></AuthLayout>}
export function SignIn(){const {data,update}=useDemo();const navigate=useNavigate();const [show,setShow]=useState(false);const [forgot,setForgot]=useState(false);return <AuthLayout><div className="auth-card"><h1>Sign in to Agency Control Center</h1><p>Access your agency workspace.</p><form onSubmit={e=>{e.preventDefault();update({signedIn:true});navigate({to:'/home'})}}><label className="field"><span>Email Address</span><input type="email" required placeholder="you@agency.com" defaultValue={data.agency.email}/></label><label className="field"><span>Password</span><div className="password-box"><input type={show?'text':'password'} required minLength={4} placeholder="Enter password"/><Button type="button" variant="ghost" size="icon" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</Button></div></label><Button className="w-full mt-4" type="submit">Sign In <ArrowRight size={15}/></Button></form><div className="auth-footer"><Button variant="link" onClick={()=>setForgot(true)}>Forgot password?</Button><Link to="/register">Register Agency</Link></div>{forgot&&<div className="inline-notice">Password reset is not connected in this demo. Use any password of at least 4 characters to explore.</div>}</div></AuthLayout>}
export function Profile(){const {data,update}=useDemo();const [editing,setEditing]=useState(false);return <Page title="Agency Profile"><div className="panel narrow"><div className="panel-top"><h2>{data.agency.name}</h2><span className="status status-approved">Active Agency Account</span></div>{editing?<GenericForm fields={agencyFields} initial={data.agency} submit="Save Profile" onCancel={()=>setEditing(false)} onSubmit={v=>{update({agency:{...data.agency,...v}});setEditing(false)}}/>:<><div className="review-list"><div><span>Agency Code</span><strong>{data.agency.code} · Permanently assigned</strong></div><div><span>Account Status</span><strong>Active Agency Account</strong></div>{agencyFields.map(f=><div key={f.name}><span>{f.label}</span><strong>{data.agency[f.name]}</strong></div>)}</div><div className="actions end"><Button variant="outline" asChild><Link to="/home">Back to Home</Link></Button><Button onClick={()=>setEditing(true)}>Edit Profile</Button></div></>}</div></Page>}
