import { Link, useNavigate } from '@tanstack/react-router';
import { Bell, Search, UserRound, ChevronDown, ArrowRight, ArrowLeft, X, Check, Copy, Download, LogOut } from 'lucide-react';
import { useState, type ReactNode, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { useDemo } from '@/lib/demo';
import { Wallet } from 'lucide-react';
import { SearchPopover, NotificationsPanel, WalletPanel, useUnread } from './global';
import { AllScreensMenu } from './all-screens';
export { Button };
export function Brand(){return <span className="brand">TAARAA<span className="brand-os"> OS</span><sup>™</sup></span>}
export function Topbar(){const {data,update}=useDemo();const [menu,setMenu]=useState(false);const [panel,setPanel]=useState('');const unread=useUnread();const toggle=(p:string)=>{setMenu(false);setPanel(panel===p?'':p)}; const navigate=useNavigate();return <header className="topbar"><Link to="/home" aria-label="TAARAA OS home"><Brand/></Link><div className="topbar-right"><AllScreensMenu/><button className="account-select" onClick={()=>setMenu(!menu)}>{data.agency.name || 'Agency'} <ChevronDown size={14}/></button><button className="icon-button" aria-label="Search" title="Search" onClick={()=>toggle('search')}><Search size={18}/></button><button className="icon-button" aria-label="CBDC Wallete" title="CBDC Wallete" onClick={()=>toggle('wallet')}><Wallet size={18}/></button><button className="icon-button bell" aria-label="Notifications" title="Notifications" onClick={()=>toggle('notif')}><Bell size={18}/>{unread>0&&<span className="badge-dot">{unread}</span>}</button><button className="icon-button" aria-label="Profile menu" title="Profile menu" onClick={()=>{setPanel('');setMenu(!menu)}}><UserRound size={18}/></button>{panel==='search'&&<SearchPopover onClose={()=>setPanel('')}/>}{panel==='notif'&&<NotificationsPanel onClose={()=>setPanel('')}/>}{panel==='wallet'&&<WalletPanel/>}{menu&&<div className="profile-menu"><Link to="/agency/profile" onClick={()=>setMenu(false)}><UserRound size={15}/> Agency profile</Link><button onClick={()=>{update({signedIn:false});setMenu(false);navigate({to:'/signin'})}}><LogOut size={15}/> Sign out</button></div>}</div></header>}
export function Page({title, parent, parentTo, children, className=''}:{title:string;parent?:string;parentTo?:string;children:ReactNode;className?:string}) {return <><Topbar/><main className={`page-wrap ${className}`}><div className="breadcrumbs"><Link to="/home">Home</Link>{parent&&<><span>/</span><Link to={parentTo || '/home' as '/home'}>{parent}</Link></>}<span>/</span><span>{title}</span></div><div className="page-heading"><span className="heading-line"/><h1>{title}</h1></div>{children}</main></>}
export function Tabs({items,value,onChange}:{items:string[];value:string;onChange:(s:string)=>void}){return <div className="tabs" role="tablist">{items.map(t=><Button key={t} role="tab" aria-selected={t===value} variant="ghost" className={t===value?'tab active':'tab'} onClick={()=>onChange(t)}>{t}</Button>)}</div>}
export function SearchField({value,onChange,placeholder='Search by name, city, or code'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="search-field"><Search size={16}/><input aria-label="Search" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
export function Status({children}:{children:string}){return <span className={`status status-${children.toLowerCase().replace(/\s+/g,'-')}`}>{children}</span>}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className={`modal ${wide?'modal-wide':''}`} role="dialog" aria-modal="true" aria-label={title}><div className="modal-top"><h2>{title}</h2><Button variant="ghost" size="icon" aria-label="Close" onClick={onClose}><X size={18}/></Button></div>{children}</div></div>}
export function Success({title,description,onClose,children}:{title:string;description:string;onClose:()=>void;children?:ReactNode}){return <Modal title={title} onClose={onClose}><div className="success-body"><div className="success-mark"><Check size={27}/></div><h3>{title}</h3><p>{description}</p><div className="actions center">{children || <Button onClick={onClose}>Done</Button>}</div></div></Modal>}
export function Field({label,name,value,onChange,type='text',required=true,placeholder,options}: {label:string;name:string;value?:string;onChange?:(v:string)=>void;type?:string;required?:boolean;placeholder?:string;options?:string[]}){return <label className="field"><span>{label}{required&&<b> *</b>}</span>{options?<select name={name} required={required} value={value ?? ''} onChange={e=>onChange?.(e.target.value)}><option value="">Select {label.toLowerCase()}</option>{options.map(o=><option key={o}>{o}</option>)}</select>:<input name={name} type={type} required={required} value={value} onChange={e=>onChange?.(e.target.value)} placeholder={placeholder || `Enter ${label.toLowerCase()}`}/>}</label>}
export function GenericForm({fields,initial={},onSubmit,submit='Save',onCancel}:{fields:{label:string;name:string;type?:string;required?:boolean;options?:string[]}[];initial?:Record<string,string>;onSubmit:(v:Record<string,string>)=>void;submit?:string;onCancel?:()=>void}){const [form,setForm]=useState(initial);const [error,setError]=useState('');return <form onSubmit={(e:FormEvent)=>{e.preventDefault();const f=e.currentTarget as HTMLFormElement;if(!f.checkValidity()){f.reportValidity();return}onSubmit(form)}} className="form-grid">{fields.map(f=><Field key={f.name} {...f} value={form[f.name]||''} onChange={v=>{setForm(s=>({...s,[f.name]:v}));setError('')}}/>)}{error&&<p className="form-error">{error}</p>}<div className="form-actions">{onCancel&&<Button type="button" variant="outline" onClick={onCancel}>Cancel</Button>}<Button type="submit">{submit} <ArrowRight size={15}/></Button></div></form>}
export function FeatureCard({icon,title,description,to}:{icon:ReactNode;title:string;description:string;to:string}){return <Link to={to as '/home'} className="feature-card"><div className="feature-icon">{icon}</div><div><h3>{title}</h3><p>{description}</p></div><span className="feature-arrow"><ArrowRight size={17}/></span></Link>}
export function Back({to='/home',children='Back'}:{to?:string;children?:ReactNode}){return <Button variant="outline" asChild><Link to={to as '/home'}><ArrowLeft size={16}/>{children}</Link></Button>}
export function PaymentChoices({value,onChange}:{value:string;onChange:(v:string)=>void}){return <div className="payment-choices">{['UPI','Google Pay','PhonePe','Bank Transfer'].map(p=><label key={p} className={value===p?'payment-option selected':'payment-option'}><input type="radio" name="payment" checked={value===p} onChange={()=>onChange(p)}/><span className="payment-icon">{p==='Google Pay'?'G':p==='PhonePe'?'P':p==='Bank Transfer'?'▤':'↗'}</span>{p}</label>)}<label className="field upi-box" style={{gridColumn:'1/-1'}}><span>UPI ID</span><input defaultValue="kraftmedia@okicici" placeholder="yourname@upi" pattern="[\w.\-]+@[\w]+" required/><small className="hint">Pay to taaraaos@upi · demo only, no real charge</small></label></div>}
export function CopyButton({value}:{value:string}){const [copied,setCopied]=useState(false);return <Button variant="outline" onClick={async()=>{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),2000)}}><Copy size={15}/>{copied?'Copied':'Copy Agency Code'}</Button>}
export function DownloadButton({value}:{value:string}){return <Button variant="outline" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([`TAARAA OS Agency Code: ${value}`],{type:'text/plain'}));a.download='taaraa-agency-code.txt';a.click();URL.revokeObjectURL(a.href)}}><Download size={15}/>Download / Save Code</Button>}
