/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as EyeStoreRouteImport } from './routes/eye-store'
import { Route as HomeRouteImport } from './routes/home'
import { Route as OohAdExchangeRouteImport } from './routes/ooh-ad-exchange'
import { Route as OohBazaarRouteImport } from './routes/ooh-bazaar'
import { Route as OohMediaBazaarRouteImport } from './routes/ooh-media-bazaar'
import { Route as OohPartnersRouteImport } from './routes/ooh-partners'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AgencyProfileRouteImport } from './routes/agency.profile'
import { Route as OohBazaarIndexRouteImport } from './routes/ooh-bazaar.index'
import { Route as OohBazaarListRouteImport } from './routes/ooh-bazaar.list'
import { Route as PartnerLoginRoleRouteImport } from './routes/partner-login.$role'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RegisterReviewRouteImport } from './routes/register.review'
import { Route as RegisterSuccessRouteImport } from './routes/register.success'
import { Route as CampaignsIdMonitorRouteImport } from './routes/campaigns.$id.monitor'
import { Route as CampaignsIdReviewRouteImport } from './routes/campaigns.$id.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const EyeStoreRoute = EyeStoreRouteImport.update({
  id: '/eye-store',
  path: '/eye-store',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const OohAdExchangeRoute = OohAdExchangeRouteImport.update({
  id: '/ooh-ad-exchange',
  path: '/ooh-ad-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const OohBazaarRoute = OohBazaarRouteImport.update({
  id: '/ooh-bazaar',
  path: '/ooh-bazaar',
  getParentRoute: () => rootRouteImport,
} as any)
const OohMediaBazaarRoute = OohMediaBazaarRouteImport.update({
  id: '/ooh-media-bazaar',
  path: '/ooh-media-bazaar',
  getParentRoute: () => rootRouteImport,
} as any)
const OohPartnersRoute = OohPartnersRouteImport.update({
  id: '/ooh-partners',
  path: '/ooh-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyProfileRoute = AgencyProfileRouteImport.update({
  id: '/agency/profile',
  path: '/agency/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OohBazaarIndexRoute = OohBazaarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OohBazaarRoute,
} as any)
const OohBazaarListRoute = OohBazaarListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => OohBazaarRoute,
} as any)
const PartnerLoginRoleRoute = PartnerLoginRoleRouteImport.update({
  id: '/partner-login/$role',
  path: '/partner-login/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterReviewRoute = RegisterReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => RegisterRoute,
} as any)
const CampaignsIdMonitorRoute = CampaignsIdMonitorRouteImport.update({
  id: '/campaigns/$id/monitor',
  path: '/campaigns/$id/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdReviewRoute = CampaignsIdReviewRouteImport.update({
  id: '/campaigns/$id/review',
  path: '/campaigns/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/eye-store': typeof EyeStoreRoute
  '/home': typeof HomeRoute
  '/ooh-ad-exchange': typeof OohAdExchangeRoute
  '/ooh-bazaar': typeof OohBazaarRouteWithChildren
  '/ooh-media-bazaar': typeof OohMediaBazaarRoute
  '/ooh-partners': typeof OohPartnersRoute
  '/register': typeof RegisterRouteWithChildren
  '/signin': typeof SigninRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/ooh-bazaar/list': typeof OohBazaarListRoute
  '/partner-login/$role': typeof PartnerLoginRoleRoute
  '/register/review': typeof RegisterReviewRoute
  '/register/success': typeof RegisterSuccessRoute
  '/ooh-bazaar/': typeof OohBazaarIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/campaigns/$id/monitor': typeof CampaignsIdMonitorRoute
  '/campaigns/$id/review': typeof CampaignsIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/eye-store': typeof EyeStoreRoute
  '/home': typeof HomeRoute
  '/ooh-ad-exchange': typeof OohAdExchangeRoute
  '/ooh-media-bazaar': typeof OohMediaBazaarRoute
  '/ooh-partners': typeof OohPartnersRoute
  '/signin': typeof SigninRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/ooh-bazaar/list': typeof OohBazaarListRoute
  '/partner-login/$role': typeof PartnerLoginRoleRoute
  '/register/review': typeof RegisterReviewRoute
  '/register/success': typeof RegisterSuccessRoute
  '/ooh-bazaar': typeof OohBazaarIndexRoute
  '/register': typeof RegisterIndexRoute
  '/campaigns/$id/monitor': typeof CampaignsIdMonitorRoute
  '/campaigns/$id/review': typeof CampaignsIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/eye-store': typeof EyeStoreRoute
  '/home': typeof HomeRoute
  '/ooh-ad-exchange': typeof OohAdExchangeRoute
  '/ooh-bazaar': typeof OohBazaarRouteWithChildren
  '/ooh-media-bazaar': typeof OohMediaBazaarRoute
  '/ooh-partners': typeof OohPartnersRoute
  '/register': typeof RegisterRouteWithChildren
  '/signin': typeof SigninRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/ooh-bazaar/list': typeof OohBazaarListRoute
  '/partner-login/$role': typeof PartnerLoginRoleRoute
  '/register/review': typeof RegisterReviewRoute
  '/register/success': typeof RegisterSuccessRoute
  '/ooh-bazaar/': typeof OohBazaarIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/campaigns/$id/monitor': typeof CampaignsIdMonitorRoute
  '/campaigns/$id/review': typeof CampaignsIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/eye-store'
    | '/home'
    | '/ooh-ad-exchange'
    | '/ooh-bazaar'
    | '/ooh-media-bazaar'
    | '/ooh-partners'
    | '/register'
    | '/signin'
    | '/agency/profile'
    | '/ooh-bazaar/list'
    | '/partner-login/$role'
    | '/register/review'
    | '/register/success'
    | '/ooh-bazaar/'
    | '/register/'
    | '/campaigns/$id/monitor'
    | '/campaigns/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/eye-store'
    | '/home'
    | '/ooh-ad-exchange'
    | '/ooh-media-bazaar'
    | '/ooh-partners'
    | '/signin'
    | '/agency/profile'
    | '/ooh-bazaar/list'
    | '/partner-login/$role'
    | '/register/review'
    | '/register/success'
    | '/ooh-bazaar'
    | '/register'
    | '/campaigns/$id/monitor'
    | '/campaigns/$id/review'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/eye-store'
    | '/home'
    | '/ooh-ad-exchange'
    | '/ooh-bazaar'
    | '/ooh-media-bazaar'
    | '/ooh-partners'
    | '/register'
    | '/signin'
    | '/agency/profile'
    | '/ooh-bazaar/list'
    | '/partner-login/$role'
    | '/register/review'
    | '/register/success'
    | '/ooh-bazaar/'
    | '/register/'
    | '/campaigns/$id/monitor'
    | '/campaigns/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  EyeStoreRoute: typeof EyeStoreRoute
  HomeRoute: typeof HomeRoute
  OohAdExchangeRoute: typeof OohAdExchangeRoute
  OohBazaarRoute: typeof OohBazaarRouteWithChildren
  OohMediaBazaarRoute: typeof OohMediaBazaarRoute
  OohPartnersRoute: typeof OohPartnersRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  SigninRoute: typeof SigninRoute
  AgencyProfileRoute: typeof AgencyProfileRoute
  PartnerLoginRoleRoute: typeof PartnerLoginRoleRoute
  CampaignsIdMonitorRoute: typeof CampaignsIdMonitorRoute
  CampaignsIdReviewRoute: typeof CampaignsIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eye-store': {
      id: '/eye-store'
      path: '/eye-store'
      fullPath: '/eye-store'
      preLoaderRoute: typeof EyeStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ooh-ad-exchange': {
      id: '/ooh-ad-exchange'
      path: '/ooh-ad-exchange'
      fullPath: '/ooh-ad-exchange'
      preLoaderRoute: typeof OohAdExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ooh-bazaar': {
      id: '/ooh-bazaar'
      path: '/ooh-bazaar'
      fullPath: '/ooh-bazaar'
      preLoaderRoute: typeof OohBazaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ooh-media-bazaar': {
      id: '/ooh-media-bazaar'
      path: '/ooh-media-bazaar'
      fullPath: '/ooh-media-bazaar'
      preLoaderRoute: typeof OohMediaBazaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ooh-partners': {
      id: '/ooh-partners'
      path: '/ooh-partners'
      fullPath: '/ooh-partners'
      preLoaderRoute: typeof OohPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/profile': {
      id: '/agency/profile'
      path: '/agency/profile'
      fullPath: '/agency/profile'
      preLoaderRoute: typeof AgencyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ooh-bazaar/': {
      id: '/ooh-bazaar/'
      path: '/'
      fullPath: '/ooh-bazaar/'
      preLoaderRoute: typeof OohBazaarIndexRouteImport
      parentRoute: typeof OohBazaarRoute
    }
    '/ooh-bazaar/list': {
      id: '/ooh-bazaar/list'
      path: '/list'
      fullPath: '/ooh-bazaar/list'
      preLoaderRoute: typeof OohBazaarListRouteImport
      parentRoute: typeof OohBazaarRoute
    }
    '/partner-login/$role': {
      id: '/partner-login/$role'
      path: '/partner-login/$role'
      fullPath: '/partner-login/$role'
      preLoaderRoute: typeof PartnerLoginRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/review': {
      id: '/register/review'
      path: '/review'
      fullPath: '/register/review'
      preLoaderRoute: typeof RegisterReviewRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/success': {
      id: '/register/success'
      path: '/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/campaigns/$id/monitor': {
      id: '/campaigns/$id/monitor'
      path: '/campaigns/$id/monitor'
      fullPath: '/campaigns/$id/monitor'
      preLoaderRoute: typeof CampaignsIdMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id/review': {
      id: '/campaigns/$id/review'
      path: '/campaigns/$id/review'
      fullPath: '/campaigns/$id/review'
      preLoaderRoute: typeof CampaignsIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OohBazaarRouteChildren {
  OohBazaarListRoute: typeof OohBazaarListRoute
  OohBazaarIndexRoute: typeof OohBazaarIndexRoute
}

const OohBazaarRouteChildren: OohBazaarRouteChildren = {
  OohBazaarListRoute: OohBazaarListRoute,
  OohBazaarIndexRoute: OohBazaarIndexRoute,
}

const OohBazaarRouteWithChildren = OohBazaarRoute._addFileChildren(
  OohBazaarRouteChildren,
)

interface RegisterRouteChildren {
  RegisterReviewRoute: typeof RegisterReviewRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterReviewRoute: RegisterReviewRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  EyeStoreRoute: EyeStoreRoute,
  HomeRoute: HomeRoute,
  OohAdExchangeRoute: OohAdExchangeRoute,
  OohBazaarRoute: OohBazaarRouteWithChildren,
  OohMediaBazaarRoute: OohMediaBazaarRoute,
  OohPartnersRoute: OohPartnersRoute,
  RegisterRoute: RegisterRouteWithChildren,
  SigninRoute: SigninRoute,
  AgencyProfileRoute: AgencyProfileRoute,
  PartnerLoginRoleRoute: PartnerLoginRoleRoute,
  CampaignsIdMonitorRoute: CampaignsIdMonitorRoute,
  CampaignsIdReviewRoute: CampaignsIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
